set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {transistor_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor_sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN V7 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN U7 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN V5 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN U5 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN U8 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN W6 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN W7 [get_ports {seg_out[0]}]

set_property PACKAGE_PIN W4 [get_ports {transistor_sel[3]}]
set_property PACKAGE_PIN V4 [get_ports {transistor_sel[2]}]
set_property PACKAGE_PIN U4 [get_ports {transistor_sel[1]}]
set_property PACKAGE_PIN U2 [get_ports {transistor_sel[0]}]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U16 [get_ports clk_out]
set_property PACKAGE_PIN V17 [get_ports reset]
