set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports input]
set_property IOSTANDARD LVCMOS33 [get_ports output]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out]

set_property PACKAGE_PIN U16 [get_ports output]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports input]
set_property PACKAGE_PIN T18 [get_ports reset]
set_property PACKAGE_PIN E19 [get_ports clk_out]
